### ISSUE TITLE
Project with Docker stuck on "waiting for Postgres to become available"

### ISSUE THREAD

**Issue by Grimm-Child** [Jean-Zombie/cookiecutter-django-wagtail#21]
## What happened?
Used Cookiecutter, went through the set up, followed the instructions. Images and containers all built with no problems, but when trying to migrate the database or anything with Postgres, it just locks up the terminal by printing "Waiting for Postgres to become available" repeatedly.

## What should've happened instead?
It should have connected and created the tables and migrations.

## Additional details
I didn't make any changes to the project that the install instructions didn't instruct me to do.

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.2
    * OS: WSL2 Ubuntu-20 distro on Windows 10
    * Python version: 3.9
    * Docker versions (if using Docker): Docker version 20.10.2, build 2291f61
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ``` "project_name": "DJ Grimmstar",
    "project_slug": "dj_grimmstar",
    "description": "Test env",
    "author_name": "Cyriina Grimm",
    "domain_name": "grimmstar.online",
    "email": "xxgrimmchildxx@gmail.com",
    "version": "0.1.0",
    "open_source_license": "MIT",
    "timezone": "EST",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "12.3",
    "js_task_runner": "Gulp",
    "cloud_provider": "None",
    "mail_service": "Mailgun",
    "use_async": "n",
    "use_drf": "n",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "n",
    "use_celery": "n",
    "use_mailhog": "n",
    "use_sentry": "n",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "y",
    "_template": "https://github.com/Jean-Zombie/cookiecutter-django-wagtail/"
    ```

![2021-01-25](https://user-images.githubusercontent.com/25069268/105676887-2523dc80-5eb9-11eb-8362-2c5b9b32e0fb.png)
![2021-01-25 (1)](https://user-images.githubusercontent.com/25069268/105676882-23f2af80-5eb9-11eb-8859-1fd17d06fd3e.png)

<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/pydanny/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by Jean-Zombie** [comment]
Hey there. Did you build your containers fist? F.e. with `docker-compose -f local.yml up --build`

**Comment by Grimm-Child** [comment]
> 
> 
> Hey there. Did you build your containers first? F.e. with `docker-compose -f local.yml up --build`

Yes, I did :]

**Comment by Jean-Zombie** [comment]
Hm. I just checked again against a fresh download with your setup choices. It runs fine on my side. Maybe your `.envs/.production/.postgres` file is responsible and therefore the `DATABASE_URL` is faulty and `psycopg2` can’t connect. I'd try to debug first in `/compose/production/django/entrypoint`.
```
[…]
until postgres_ready; do
  echo $DATABASE_URL  # add this line
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'
[…]
```
Try running the container again. Does it give you a postgres url?

**Comment by Grimm-Child** [comment]
After 7 attempts at getting it to run, uninstalling/reinstalling my Ubuntu set up and dev environment, a lot of Googling, and a few bouts of hair pulling, I got it working. It was indeed an issue on my end; I had jumped straight to "Setting up locally with Docker" every time. It, for some reason, wasn't obvious to me that going through "Setting up locally" was a required step :sweat_smile:

My bad :sweat:

**Comment by Jean-Zombie** [comment]
All good. Glad it could be solved!

**Comment by yashinshekh** [comment]
it seemed like the volume is already present and it is skipping the init process for postgres. remove the volume and it should work fine

docker-compose down --volumes
